### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by hackervera** [boutier/mosh#1]
Tylers-MacBook-Pro:~ t$ mosh -6 tyler@6.tylergillies.club
IO::Socket: Unsupported socket domain at /usr/local/bin/mosh line 185.
ssh_exchange_identification: Connection closed by remote host
/usr/local/bin/mosh: Did not find remote IP address (is SSH ProxyCommand disabled?).
Tylers-MacBook-Pro:~ t$ ping6 6.tylergillies.club
PING6(56=40+8+8 bytes) fc56:ea60:10ed:a650:8393:baab:2b1b:9888 --> fc4d:b040:afaa:413f:8dd5:64b9:d142:7869
16 bytes from fc4d:b040:afaa:413f:8dd5:64b9:d142:7869, icmp_seq=0 hlim=42 time=31.034 ms

**Comment by hackervera** [comment]
use IO::Socket::INET6;

I would suggest sticking it at line 39, right below
use IO::Socket;

**Comment by boutier** [comment]
Does "suggest" means "this solve the problem"?
And, since the problem is due to the perl script, it should already be present in the standard mosh, no? I should go into the script and remove the -4 and -6 options, since mosh will use the two protocols anyway.

**Comment by hackervera** [comment]
I copy and pasted that from another thread on the mainline.

**Comment by boutier** [comment]
Pushed, thanks.
