### ISSUE TITLE
freebsd support

### ISSUE THREAD

**Issue by TimCook1** [boutier/mosh#2]
Just tried doing a pull from your repo as well as keithw's about 5 minutes ago.  I get an error compiling from your source (no error from KeithW) on freebsd 10.1-P10, gcc49-4.9.4.s20150701.  Let me know if there's any other info I can provide.  I have not dug in to see if it's something simple or not, working on that next:

  CXX      network.o
In file included from network.cc:52:
./network.h:121:7: error: use of undeclared identifier 'UINT64_MAX'
        rto( UINT64_MAX ), last_heard( 0 ), next_probe( 0 ), idle_time( 0 ),
             ^
network.cc:146:19: error: use of undeclared identifier 'UINT64_MAX'
      flow->rto = UINT64_MAX;
                  ^
network.cc:150:23: error: use of undeclared identifier 'UINT64_MAX'
    if ( flow->rto == UINT64_MAX ) {
                      ^
network.cc:1048:22: error: use of undeclared identifier 'UINT64_MAX'
    flow_info->rto = UINT64_MAX;
                     ^
4 errors generated.
**\* Error code 1

Stop.
make[3]: stopped in /usr/src/mosh/src/network
**\* Error code 1

Stop.
make[2]: stopped in /usr/src/mosh/src
**\* Error code 1

Stop.
make[1]: stopped in /usr/src/mosh
**\* Error code 1

Stop.
make: stopped in /usr/src/mosh

**Comment by boutier** [comment]
Thanks for the feedback,

> ./network.h:121:7: error: use of undeclared identifier 'UINT64_MAX'

This is defined in stdint.h, as well in Linux and OSX, so I thought it was standard (eh, _std_int)...  I will use the "uint64_t( -1 )" construction instead, which is more readable than the "#defined" value:

  #define UINT64_MAX        18446744073709551615ULL

(for now, I must take a train!)

**Comment by TimCook1** [comment]
Just so you know, when I was testing last night and I statically defined UINT64_MAX, it bombed out with this:

./addresses.h:117:66: error: use of undeclared identifier 'u_int32_t'
      return ( sa.sa_family == AF_INET && sin.sin_addr.s_addr == INADDR_ANY ) ||
                                                                 ^
/usr/include/netinet/in.h:46:22: note: expanded from macro 'INADDR_ANY'
#define INADDR_ANY              (u_int32_t)0x00000000

**Comment by boutier** [comment]
mmm... can you try

```
make -k
```

such that we will have all errors in one shot?

> UINT64_MAX

Now fixed, but it's perhaps not the best solution: some indicates that we should use "#include <cstdint>" with C++ code, but (1) it causes some others compilation problems on my Linux, and (2) it will not be uniform with the original mosh code.  For the record:

```
http://lists.freebsd.org/pipermail/freebsd-bugs/2012-December/051270.html
```

> ./addresses.h:117:66: error: use of undeclared identifier 'u_int32_t'

Can you try with "#include <sys/types.h>" just before "#include <netinet/in.h>"?

**Comment by TimCook1** [comment]
I saw the <cstdint> suggestions as well and it generated problems on FreeBSD and didn't seem to fix the issue anyways.  I'm by no means a coder although once upon a time I dabbled - I'm curious if it's just an #include issue.

stdint.h on FreeBSD has the following reference to UINT64_MAX:
/\* GNU and Darwin define this and people seem to think it's portable */
#if defined(UINTPTR_MAX) && defined(UINT64_MAX) && (UINTPTR_MAX == UINT64_MAX)
#define __WORDSIZE              64
#else
#define __WORDSIZE              32
#endif`

however, it also includes:
#include <machine/_stdint.h>

which literally only contains the following plus some comments:
#include <x86/_stdint.h>

which finally actually defines it:
#ifdef **LP64**
#define INT64_MIN       (-0x7fffffffffffffff-1)
#define INT64_MAX       0x7fffffffffffffff
#define UINT64_MAX      0xffffffffffffffff
#else
#define INT64_MIN       (-0x7fffffffffffffffLL-1)
#define INT64_MAX       0x7fffffffffffffffLL
#define UINT64_MAX      0xffffffffffffffffULL
#endif`

That's about as far as I got last night before I decided I should probably stop trying to pretend I know C.

make -k (without any changes besides statically defining UINT64_MAX):

make  all-recursive
Making all in src
Making all in protobufs
make  all-am
Making all in util
Making all in crypto
Making all in terminal
Making all in network
  CXX      transportsender.o
In file included from transportsender.cc:39:
In file included from ./transportsender.h:40:
In file included from ./network.h:49:
./addresses.h:117:66: error: use of undeclared identifier 'u_int32_t'
      return ( sa.sa_family == AF_INET && sin.sin_addr.s_addr == INADDR_ANY ) ||
                                                                 ^
/usr/include/netinet/in.h:46:22: note: expanded from macro 'INADDR_ANY'
#define INADDR_ANY              (u_int32_t)0x00000000
                                 ^
1 error generated.
**\* Error code 1 (continuing)
  CXX      compressor.o
  CXX      addresses.o
In file included from addresses.cc:36:
./addresses.h:117:66: error: use of undeclared identifier 'u_int32_t'
      return ( sa.sa_family == AF_INET && sin.sin_addr.s_addr == INADDR_ANY ) ||
                                                                 ^
/usr/include/netinet/in.h:46:22: note: expanded from macro 'INADDR_ANY'
#define INADDR_ANY              (u_int32_t)0x00000000
                                 ^
1 error generated.
**\* Error code 1 (continuing)
`all' not remade because of errors.
Making all in statesync
  CXX      completeterminal.o
  CXX      user.o
  AR       libmoshstatesync.a
Making all in frontend
  CXX      mosh-client.o
  CXX      stmclient.o
  CXX      terminaloverlay.o
In file included from terminaloverlay.cc:39:
In file included from ./terminaloverlay.h:37:
In file included from ./../network/network.h:49:
./../network/addresses.h:117:66: error: use of undeclared identifier 'u_int32_t'
      return ( sa.sa_family == AF_INET && sin.sin_addr.s_addr == INADDR_ANY ) ||
                                                                 ^
/usr/include/netinet/in.h:46:22: note: expanded from macro 'INADDR_ANY'
#define INADDR_ANY              (u_int32_t)0x00000000
                                 ^
1 error generated.
**\* Error code 1 (continuing)
make[3]: don't know how to make ../network/libmoshnetwork.a (continuing)
  CXX      mosh-server.o
all' not remade because of errors.
Making all in examples
Making all in tests
Making all in scripts
Making all in man
Making all in conf

**Comment by TimCook1** [comment]
> Can you try with `"#include <sys/types.h>"` just before `"#include <netinet/in.h>"`?

That appears to be clean after adding that plus the static define of UINT64_MAX.  I'll do another pull shortly to test with your fix of uint64_t( -1 ) rather than defining it statically.  Last make -k:

make  all-recursive
Making all in src
Making all in protobufs
make  all-am
Making all in util
Making all in crypto
Making all in terminal
Making all in network
  CXX      network.o
  CXX      networktransport.o
  CXX      transportsender.o
  CXX      addresses.o
  AR       libmoshnetwork.a
Making all in statesync
Making all in frontend
  CXX      mosh-client.o
  CXX      stmclient.o
  CXX      terminaloverlay.o
  CXXLD    mosh-client
  CXX      mosh-server.o
  CXXLD    mosh-server
Making all in examples
Making all in tests
Making all in scripts
Making all in man
Making all in conf

**Comment by TimCook1** [comment]
Just did a fresh pull and then added the types.h and it came back clean.

**Comment by boutier** [comment]
Strangely enough, the "<>" quotations does not appear in your message:

> however, it also includes:
> #include
> 
> which literally only contains the following plus some comments:
> #include

:-/

> That's about as far as I got last night before I decided I should probably stop trying to pretend I know C.

Well, in fact, C++.  I don't think that the C++ compiler use the same headers than the C compiler.  Oh, perhaps using the following also solves the problem:

extern "C" {
    #include "stdint.h"
}

> That appears to be clean after adding that plus

Excellent.  I do the patch, merge with mosh, and commit some stuff.

Thanks.

**Comment by TimCook1** [comment]
Ya, markdown is completely messing with my posts.  Apparently my github comment-fu is lacking today.

Also, the INET6 thing breaks FreeBSD.  Commenting it out and it works fine:
Can't locate IO/Socket/INET6.pm in @INC (you may need to install the IO::Socket::INET6 module) (@INC contains: /usr/local/lib/perl5/site_perl/mach/5.20 /usr/local/lib/perl5/site_perl /usr/local/lib/perl5/5.20/mach /usr/local/lib/perl5/5.20 /usr/local/lib/perl5/site_perl/5.20 /usr/local/lib/perl5/site_perl/5.20/mach .) at /usr/local/bin/mosh line 39.
BEGIN failed--compilation aborted at /usr/local/bin/mosh line 39.

# perl --version

This is perl 5, version 20, subversion 2 (v5.20.2) built for amd64-freebsd-thread-multi

This is more of a request than anything else - any chance we can get some better versioning?  It's almost impossible to determine exactly what build a system has on it when everything just returns 1.2.4a with a mosh --version.

**Comment by boutier** [comment]
> Also, the INET6 thing breaks FreeBSD

That's not fair!

> perl --version
> 
> This is perl 5, version 20, subversion 2 (v5.20.2)

ok, let drop that patch.  Anyway, that one (in the trunc) should be better:

```
e7903f0de2b93f729fbf6b524145e4d4309c95f3
```

> This is more of a request than anything else - any chance we can get some better versioning?

I've just merged the current mosh tree, so there is a good versioning system, with the current git hash.  Would you like to have something like "mpmosh_" instead of "mosh_"?

**Comment by TimCook1** [comment]
Well, I'm just thinking from a users perspective, how do they tell what
specific build of mosh they're on?  If mosh --version just returns:
mosh 1.2.4a
Copyright 2012 Keith Winstein mosh-devel@mit.edu
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

If I'm a regular user, I'm probably not thinking about doing a git hash,
I'm looking at the --version output.  If it's not feasible to rev the
--version output, I get it.  I consider it more of a nice-to-have.  But
then again these aren't official releases so maybe I should just get over
it :)  It probably would be good to have something in there about mpmosh
though given that in my brief testing the non-mpmosh builds didn't seem to
want to talk to mpmosh builds (client or server).

**Comment by TimCook1** [comment]
NVM, just did a fresh pull, I see:

# mosh --version

mosh 1.2.4.95rc2 [build mosh-1.2.4-169-g42c4f3d]
Copyright 2012 Keith Winstein mosh-devel@mit.edu

That's exactly what I was looking for.  Although I would still probably try
to call out mpmosh until it makes it to an official release unless mpmosh
is compatible with non-mpmosh and I just needed to do more testing to
figure out why it wasn't working.

**Comment by boutier** [comment]
> Although I would still probably try to call out mpmosh

Done.

> unless mpmosh is compatible

Alas it isn't.  But it should be possible: I have to add an option to the server and the client to allow or not multipath, and then the perl script has to select the compatible options…
